baseUrl = "https://wubh2012.github.io"
languageCode = "en-us"
title = "AALMIX's Blog"
theme = "echo"
DefaultContentLanguage = "cn"
# è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å«ä¸­æ–‡/æ—¥æ–‡/éŸ©æ–‡ï¼Œè¯¥å‚æ•°ä¼šå½±å“æ‘˜è¦å’Œå­—æ•°ç»Ÿè®¡åŠŸèƒ½ï¼Œå»ºè®®è®¾ç½®ä¸º true
hasCJKLanguage = true
# è®¾ç½®é¡µé¢ç”Ÿæˆå½¢å¼ï¼Œå°†é»˜è®¤çš„ç½‘ç«™è·¯å¾„/ä¿®æ”¹æˆ.html
uglyURLs = true
googleAnalytics = ""      # UA-XXXXXXXX-X

## è¯„è®ºç³»ç»Ÿ
changyanAppid = "" # Changyan app id             # ç•…è¨€
changyanAppkey = "" # Changyan app key
disqusShortname = "AALMIX-blog" # disqus account name
livereUID = "" # LiveRe UID                  # æ¥å¿…åŠ›

[markup.highlight]
codeFences = true # é«˜äº® markdown çš„ä»£ç å—
guessSyntax = true # é«˜äº® markdown ä¸­æ²¡æœ‰æ ‡æ³¨è¯­è¨€çš„ä»£ç å—
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "manni"
tabWidth = 2

# https://gohugo.io/content-management/urls/#aliases
[permalinks]
posts = "/:filename"

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[services.rss]
limit = 20

[author]
name = "AALMIX"
avatar = "https://avatars.githubusercontent.com/u/22315624?s=400&u=0f4091c87fa6cb1f7ed21d691a5e0bc3eb0b0814&v=4"
bio = " ä¸€åæ™®é€šçš„ç¨‹åºå‘˜ ğŸ˜€"
homepage = "https://aalmix.com/"

[params]
favicon = "https://avatars.githubusercontent.com/u/22315624?s=460&v=4"
keywords = "AALMIX, æ°´æœèŠ‹å¤´, C#, Asp.net, Asp.net MVC, android, vue, java, web develoment"
description = "AALMIX, aalmix blog, aalmix ç‹¬ç«‹åšå®¢ï¼Œæ°´æœèŠ‹å¤´"
toc = true
navItems = [
  ["HOME", "/"],
  ["ARCHIVE", "/posts.html"],
  ["ABOUT", "/about.html"],
  ["RSS", "/atom.xml"]
]
# rss å…¨æ–‡è¾“å‡º
rssFullContent = true
uglyURLs = true
busuanzi = true # æ˜¯å¦ä½¿ç”¨ä¸è’œå­ç»Ÿè®¡ç«™ç‚¹è®¿é—®é‡
staticCDNPrefix = "https://cdn.bootcss.com/font-awesome/5.11.2"
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
postAds = ""
#profileAds = '<div class="bg-white shadow"><img class=" object-cover w-auto mx-auto mt-6" src="https://blog-1251237404.cos.ap-guangzhou.myqcloud.com/20190424153337.png" alt="å¾®ä¿¡æ‰“èµ"></div>'
notFoundAds = ''

# å¼€å¯ç‰ˆæƒå£°æ˜ï¼Œåè®®åå­—å’Œé“¾æ¥éƒ½å¯ä»¥æ¢
[params.cc]
name = "ç½²å - éå•†ä¸šæ€§ä½¿ç”¨ 4.0 å›½é™… (CC BY-NC 4.0)"
link = "https://creativecommons.org/licenses/by-nc/4.0/deed.zh"

# æ–‡ç« æ‰“èµ
[params.reward]
enable = false
title = "æ‰“èµ"
wechat = "" # å¾®ä¿¡äºŒç»´ç 
alipay = "" # æ”¯ä»˜å®äºŒç»´ç 

############## è¯„è®ºç³»ç»Ÿ  start ##############


[params.utterances] # https://utteranc.es/
enable = true
owner = "wubh2012" # Your GitHub ID
repo = "https://github.com/wubh2012/wubh2012.github.io" # The repo to store comments
theme = "github-light"
issueterm = "pathname"

#[params.giscus] # https://giscus.app
#enable = false
#repo = "forecho/hugo-blog" # Repo where the comments will live
#repo_id = "<data-repo-id>" # Repo where the comments will live
#category = "Announcements" # Repo where the comments will live
#category_id = "<data-category-id>" # Repo where the comments will live
#mapping = "pathname" # How Utterances will match comment to page
#theme = "light" # What theme to use
#reactions_enabled = "1" # Enable reactions
#emit_metadata= "0" # Emit metadata
#lang = "zh-CN" # Language

############ è¯„è®ºç³»ç»Ÿ  end ##############
## ç¤¾äº¤é“¾æ¥
[social]
github = "wubh2012"
#jsfiddle = "forecho"
#codepen = "forecho"
#dribbble = "forecho"
#behance = "forecho"
#flickr = "forecho"
#instagram = "forecho"
#youtube = "forecho"
#vimeo = "forecho"
#vine = "forecho"
#medium = "forecho"
#wordpress = "forecho"
#tumblr = "forecho"
#linkedin = "forecho"
#slideshare = "forecho"
#stackoverflow = "forecho"
#reddit = "forecho"
#pinterest = "forecho"
#weibo = "forecho"
#facebook = "forecho"
twitter = "twbh_wubh"
cnblogs = "wubh"
#douban = "ipzone"
rss = "/atom.xml"